apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpu-metric-test-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cpu-metric-test
  template:
    metadata:
      labels:
        app: cpu-metric-test
    spec:
      serviceAccountName: cpu-metric-test-svc
      containers:
      - name: cpu-metric-test
        image: acrfhl202503.azurecr.io/cpu-metric-test:latest
        ports:
        - containerPort: 8080
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: workload
                operator: In
                values:
                - app
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cpu-metric-test-svc
  namespace: rapi-cpu-experiments
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
    name: metric-role
    namespace: rapi-cpu-experiments
rules:
    - apiGroups:
        - ''
      resources:
        - 'pods'
      verbs:
        - 'create'
        - 'delete'
        - 'get'
        - 'list'
        - 'patch'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: metric-rolebind
subjects:
    - kind: ServiceAccount
      name: cpu-metric-test-svc
      namespace: rapi-cpu-experiments
roleRef:
    kind: Role
    name: metric-role
    apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Service
metadata:
  name: cpu-metric-test-service
spec:
  selector:
    app: cpu-metric-test
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer